name: iOS Unsigned IPA (Debug)

on:
  workflow_dispatch:

jobs:
  build-unsigned-debug:
    runs-on: macos-14

    env:
      SCHEME: appdb
      CONFIGURATION: Release
      BUILD_DIR: ${{ github.workspace }}/build
      OUT_DIR: ${{ github.workspace }}/unsigned_out
      PROJECT_OR_WORKSPACE: appdb.xcodeproj
      USE_WORKSPACE: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15 (fallback ok)
        run: |
          XCODE="/Applications/Xcode_15.4.app"
          if [ -d "$XCODE" ]; then sudo xcode-select -s "$XCODE"; fi
          xcodebuild -version

      - name: Detect CocoaPods / workspace
        run: |
          set -e
          if [ -f "Podfile" ] || [ -f "appdb/Podfile" ]; then
            echo "CocoaPods detected."
            sudo gem install cocoapods --no-document
            POD_DIR="."
            [ -f "appdb/Podfile" ] && POD_DIR="appdb"
            (cd "$POD_DIR" && pod install)
            echo "PROJECT_OR_WORKSPACE=$POD_DIR/appdb.xcworkspace" >> $GITHUB_ENV
            echo "USE_WORKSPACE=true" >> $GITHUB_ENV
          else
            echo "No Podfile found; using .xcodeproj"
            echo "PROJECT_OR_WORKSPACE=appdb.xcodeproj" >> $GITHUB_ENV
            echo "USE_WORKSPACE=false" >> $GITHUB_ENV
          fi

      - name: Build (no code signing)
        run: |
          set -e
          mkdir -p "$BUILD_DIR"
          if [ "$USE_WORKSPACE" = "true" ]; then
            xcodebuild               -workspace "$PROJECT_OR_WORKSPACE"               -scheme "$SCHEME"               -configuration "$CONFIGURATION"               -sdk iphoneos               -destination 'generic/platform=iOS'               BUILD_DIR="$BUILD_DIR"               CONFIGURATION_BUILD_DIR="$BUILD_DIR/Release-iphoneos"               SUPPORTS_MACCATALYST=NO               CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""               clean build | xcpretty || exit 1
          else
            xcodebuild               -project "$PROJECT_OR_WORKSPACE"               -scheme "$SCHEME"               -configuration "$CONFIGURATION"               -sdk iphoneos               -destination 'generic/platform=iOS'               BUILD_DIR="$BUILD_DIR"               CONFIGURATION_BUILD_DIR="$BUILD_DIR/Release-iphoneos"               SUPPORTS_MACCATALYST=NO               CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""               clean build | xcpretty || exit 1
          fi

      - name: Show built app bundle contents
        run: |
          APP_PATH=$(find "$BUILD_DIR/Release-iphoneos" -maxdepth 2 -type d -name "*.app" | head -n 1)
          echo "APP_PATH=$APP_PATH"
          if [ -z "$APP_PATH" ]; then exit 1; fi
          ls -la "$APP_PATH"
          if [ -f "$APP_PATH/Info.plist" ]; then
            /usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$APP_PATH/Info.plist" || true
            /usr/libexec/PlistBuddy -c 'Print :CFBundlePackageType' "$APP_PATH/Info.plist" || true
          else
            echo "NO Info.plist FOUND in $APP_PATH"
            exit 1
          fi

      - name: Package unsigned IPA
        run: |
          set -e
          mkdir -p "$OUT_DIR"
          APP_PATH=$(find "$BUILD_DIR/Release-iphoneos" -maxdepth 2 -type d -name "*.app" | head -n 1)
          WORK="$OUT_DIR/payloaddir"
          mkdir -p "$WORK/Payload"
          cp -R "$APP_PATH" "$WORK/Payload/"
          find "$WORK/Payload" -type d -name "_CodeSignature" -exec rm -rf {} + || true
          find "$WORK/Payload" -type f -name "embedded.mobileprovision" -delete || true
          cd "$WORK"
          /usr/bin/zip -9 -r "../appdb-unsigned.ipa" Payload
          ls -lah "$OUT_DIR"

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: appdb-unsigned-ipa-debug
          path: ${{ github.workspace }}/unsigned_out/appdb-unsigned.ipa
