name: Build IPA

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install
          bundle exec pod install
        working-directory: . # Adjust this path to the directory containing your Gemfile

      - name: Build and archive the project
        run: |
          xcodebuild -workspace appdb.xcworkspace \
                      -scheme appdb \
                      -sdk iphoneos \
                      -configuration Release \
                      -archivePath $PWD/build/appdb.xcarchive \
                      clean archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                      -archivePath $PWD/build/appdb.xcarchive \
                      -exportPath $PWD/build \
                      -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: appdb-IPA
          path: build/appdb.ipa
