name: Build IPA

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Find .p12 file
        id: find-p12
        run: |
          p12_file=$(find . -name "*.p12" | head -n 1)
          echo "p12_file=$p12_file" >> $GITHUB_ENV

      - name: Find provisioning profile
        id: find-provisioning
        run: |
          provisioning_profile=$(find . -name "*.mobileprovision" | head -n 1)
          echo "provisioning_profile=$provisioning_profile" >> $GITHUB_ENV

      - name: Install Signing Certificate
        run: |
          security create-keychain -p actions build.keychain
          security import "$p12_file" -t agg -k ~/Library/Keychains/build.keychain -P 123456 -A
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p actions ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k actions ~/Library/Keychains/build.keychain

      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$provisioning_profile" ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build and archive the project
        run: |
          xcodebuild -project appdb.xcodeproj \
                      -scheme appdb \
                      -sdk iphoneos \
                      -configuration Release \
                      -archivePath $PWD/build/appdb.xcarchive \
                      clean archive \
                      -allowProvisioningUpdates

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                      -archivePath $PWD/build/appdb.xcarchive \
                      -exportPath $PWD/build \
                      -exportOptionsPlist ExportOptions.plist \
                      -allowProvisioningUpdates

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: appdb-IPA
          path: build/appdb.ipa
